### ISSUE TITLE
Change in fail2ban iredmail url

### ISSUE THREAD

**Issue by MRTRALHA** [killmasta93/tutorials#1]
Hello,

The new url for the postfix-pregreet-iredmail filter for fail2ban is:

https://github.com/iredmail/iRedMail/blob/master/samples/fail2ban/filter.d/postfix-pregreet.iredmail.conf

or

https://raw.githubusercontent.com/iredmail/iRedMail/master/samples/fail2ban/filter.d/postfix-pregreet.iredmail.conf

Thanks,

MRT

**Comment by killmasta93** [comment]
thank you fixed
