### ISSUE TITLE
Malware Patrol does not offer free subscription anymore

### ISSUE THREAD

**Issue by luke5sky** [killmasta93/tutorials#2]
Hi,

i may be mistaken, but i think malware patrol does not offer a free subscription anymore.
Tutorial Line is:
`Then nano the user conf add the receipt number to do so wait till you get an email [malware patrol](https://www.malwarepatrol.net/free-guard-upgrade-option/) then go to free`

Links works, but if you go to free sub you get a 404.

**Comment by killmasta93** [comment]
Hi there have you tried https://www.malwarepatrol.net/free-guard-block-list/

**Comment by luke5sky** [comment]
Hi,

yes this link gives me the 404:
![grafik](https://user-images.githubusercontent.com/27992191/215446890-7a6de5ea-dbc7-41bc-8de5-8ace101c31ac.png)

**Comment by killmasta93** [comment]
can you try this one https://www.malwarepatrol.net/risk-indicator-feeds-registration/

**Comment by luke5sky** [comment]
This one works 
![Screenshot_20230130-180956](https://user-images.githubusercontent.com/27992191/215546203-acdce0b3-a14c-4369-9850-e4c98859f227.png)
